baseURL = 'https://eens.netlify.app/'
languageCode = 'en-us'
title = 'My New Hugo Site'
contentDir = "content"
theme = "docsy"

[module]
  [[module.imports]]
    path = "github.com/FortAwesome/Font-Awesome"
    disable = false
